# Generated by Django 6.0.2 on 2026-02-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='angry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='thumbs_up_count',
            field=models.IntegerField(default=0),
        ),
    ]
